name: example
description: Example project for flutter_upchunk.

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  flutter_upchunk:
    path: ../
  image_picker: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
