name: example
description: Example project for flutter_upchunk.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  flutter_upchunk: ^0.1.3
  image_picker: ^0.6.7+12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
